@env = development

@access_token = <paste_access_token_here>

### login user
POST http://localhost:3000/auth/password-reset
Content-Type: application/json

{
  "email": "otwanemar12k254@gmail.com",
  "password": "Mark1234@#$.",
  "role":"ADMIN"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "otwanemark254@gmail.com",
  "password": "Mark1234@#$.",
  "role":"ADMIN"
}

### add product to cart

POST http://http://localhost:3000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoib3R3YW5lbWFyazAwM0BnbWFpbC5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTAzNDI3NjksImV4cCI6MTc1MDM0NjM2OX0.ovSllvt008DWX5dcZii11_Z77ZEGDcUPaCmyYwFzeNE
Content-Type: application/json

{
  "id": 1,
}

### Create a product (admin only)
POST http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoib3R3YW5lbWFyazI1NEBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTAzNDA3NzMsImV4cCI6MTc1MDM0NDM3M30.mZkPC6kgT_dpcHeOHqjHJJUbsF1HAlU4CjZt0YwBsyI
Content-Type: application/json


  {
    "name": "Wireless Headphones",
    "description": "Noise-cancelling over-ear Bluetooth headphones with 40-hour battery life.",
    "price": 89.99,
    "imageUrl": "https://via.placeholder.com/150?text=Headphones",
    "stock": 50
  }