@env = development

### login user

POST http://localhost:3000/auth/password-reset
Content-Type: application/json

{
  "email": "karenmasila7@gmail.com",
  "password": "Mark1234@#$.",
  "role": "CUSTOMER"
}

###
POST http://localhost:3000/auth/password-reset
Content-Type: application/json

{
  "email": "otwanemark254@gmail.com",
  "password": "Mark1234@#$.",
  "role":"ADMIN"
}

### add product to cart

POST http://localhost:3000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoib3R3YW5lbWFyazI1NEBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTAzNjIzNDMsImV4cCI6MTc1MDM2NTk0M30.XRiedCyVss_DRSyx4lA2ZWR25pG2Ie2mTPA9Sv7esaE
Content-Type: application/json

{
  "id": 1,
}

### Create a product (admin only)

POST http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoib3R3YW5lbWFyazI1NEBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTAzNjIzNDMsImV4cCI6MTc1MDM2NTk0M30.XRiedCyVss_DRSyx4lA2ZWR25pG2Ie2mTPA9Sv7esaE
Content-Type: application/json


  {
    "name": "Wireless Headphones",
    "description": "Noise-cancelling over-ear Bluetooth headphones with 40-hour battery life.",
    "price": 89.99,
    "imageUrl": "https://via.placeholder.com/150?text=Headphones",
    "stock": 50
  }

###delete a product
POST http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoib3R3YW5lbWFyazI1NEBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTAzNjIzNDMsImV4cCI6MTc1MDM2NTk0M30.XRiedCyVss_DRSyx4lA2ZWR25pG2Ie2mTPA9Sv7esaE
Content-Type: application/json


  {
    "name": "Wireless Headphones",
    "description": "Noise-cancelling over-ear Bluetooth headphones with 40-hour battery life.",
    "price": 89.99,
    "imageUrl": "https://via.placeholder.com/150?text=Headphones",
    "stock": 50
  }

###update product

PATCH  http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoib3R3YW5lbWFyazI1NEBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTAzNjIzNDMsImV4cCI6MTc1MDM2NTk0M30.XRiedCyVss_DRSyx4lA2ZWR25pG2Ie2mTPA9Sv7esaE
Content-Type: application/json


  {
    "name": "Wireless Headphones",
    "description": "Noise-cancelling over-ear Bluetooth headphones with 40-hour battery life.",
    "price": 89.99,
    "imageUrl": "https://via.placeholder.com/150?text=Headphones",
    "stock": 50
  }
